name: Build

on:
  push:
    branches:
      - main

jobs:
  build:
    name: Build & SonarQube Scan
    runs-on: self-hosted   # ðŸ”¥ IMPORTANT
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0   # Required for proper Sonar analysis

      - name: SonarQube Scan
        uses: sonarsource/sonarqube-scan-action@master
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          SONAR_HOST_URL: http://localhost:9000

      - uses: actions/setup-node@v3
        with:
          node-version: '16'

      - run: npm install

      - name: Docker build and push
        run: |
          docker build -t swiggy-clone .
          docker tag swiggy-clone sudhirkumar123/swiggy-clone:latest
          echo "${{ secrets.DOCKERHUB_TOKEN }}" | docker login -u "${{ secrets.DOCKERHUB_USERNAME }}" --password-stdin
          docker push sudhirkumar123/swiggy-clone:latest
        env:
          DOCKER_CLI_ACI: 1

          
